@startuml

title Sequence : switch autor

actor Administrateur as Ad
participant Controller as C
participant Model as M

participant SGBD as bdd
ref over Ad,C,M,bdd : Se connecter
Ad->C:changerAuteurPost(idPost, idAuteur)
activate C
C->M: changerAuteur(idPost, IdAuteur)
deactivate C
activate M
M->bdd: Exécution de la requete
activate bdd
bdd-->M:Réponse
deactivate bdd
M-->C:Post mis à jour
deactivate M
activate C
C-->Ad: redirection back_office
deactivate C





@enduml