-- MySQL Script generated by MySQL Workbench
-- Wed Jul 15 17:35:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blop_pro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `blop_pro` ;

-- -----------------------------------------------------
-- Schema blop_pro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blop_pro` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `blop_pro` ;

-- -----------------------------------------------------
-- Table `blop_pro`.`user_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blop_pro`.`user_status` ;

CREATE TABLE IF NOT EXISTS `blop_pro`.`user_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blop_pro`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blop_pro`.`user` ;

CREATE TABLE IF NOT EXISTS `blop_pro`.`user` (
  `id` INT NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_user_status1`
    FOREIGN KEY (`user_status_id`)
    REFERENCES `blop_pro`.`user_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blop_pro`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blop_pro`.`post` ;

CREATE TABLE IF NOT EXISTS `blop_pro`.`post` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `resume` TEXT(1000) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blop_pro`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blop_pro`.`comment_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blop_pro`.`comment_status` ;

CREATE TABLE IF NOT EXISTS `blop_pro`.`comment_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'wait',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blop_pro`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blop_pro`.`comment` ;

CREATE TABLE IF NOT EXISTS `blop_pro`.`comment` (
  `id` INT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `post_id` INT NOT NULL DEFAULT 0,
  `comment_status_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blop_pro`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_comment_status1`
    FOREIGN KEY (`comment_status_id`)
    REFERENCES `blop_pro`.`comment_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blop_pro`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
